### ISSUE TITLE
User Story 20, User adds an item to the cart

### ISSUE THREAD

**Issue by iandouglas** [pschlatt/DuckDuckBooze#56]
```
As a visitor or registered user
When I visit an item's show page from the items catalog
I see a link or button to add this item to my cart
And I click its link or button
I am returned to the item index page
I see a flash message indicating the item has been added to my cart
The navigation bar increments my cart counter
```

DO THESE STORIES FIRST:
- User Story 16, Item Show Page

### Checklist:

- [ ] base tests are written
- [ ] base code is written to pass tests
- [ ] edge case ("sad path") tests written (if required)
- [ ] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #57

child of #82

depends on #62

**Comment by chitasan** [comment]
Do I need this to complete user story 2 re cart counter 
-Chi
